{% set name = "PyVISA-py" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70fdf68e6dabd45dab28ddcd73460d66c525acd7ff6d66a59c4dd8ff8afc7214

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pyvisa >=1.11.0
    - pyserial
    - pyusb
    - typing_extensions
    - importlib-metadata

test:
  imports:
    - pyvisa
    - pyvisa.testsuite
    - pyvisa_py
    - pyvisa_py.protocols
    - pyvisa_py.testsuite
  commands:
    # fails because of wrong versioning number in seutp.cfg
    # issue raised with project maintainers
    - pip check
    - python -c "import pyvisa_py.testsuite as ts; import unittest; unittest.TextTestRunner().run(ts.testsuite())"
    # backend issue with running the below test due to how
    # docker runs and pyvisa detects available visa backends
    # - python -c "import pyvisa; rm = pyvisa.ResourceManager('@py')"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pyvisa/pyvisa-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python VISA bindings for GPIB, RS232, and USB instruments

  description: |
    A PyVISA backend that implements a large part of the "Virtual
    Instrument Software Architecture" (VISA) in pure Python (with the
    help of some nice cross platform libraries python packages!).
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/pyvisa/pyvisa-py

extra:
  recipe-maintainers:
    - MatthieuDartiailh
    - mtsolmn
    - greyltc
