{% set name = "PyVISA-py" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98b55fc57d4c15ba211fd547da4b9c8c9684d654e5569fc002de29f313b2da5c

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyvisa >=1.10.1
    - pyserial
    - pyusb
    - typing_extensions
    - importlib-metadata

test:
  imports:
    - pyvisa
    - pyvisa.testsuite
  commands:
    #- pip check
    - python -c "import pyvisa.testsuite as ts; ts.run()"
    - python -c "import visa; rm = visa.ResourceManager('@py')"
  requires:
    - pip
    - pytest
    - pyvisa
    - pyvisa-py

about:
  home: https://github.com/pyvisa/pyvisa-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python VISA bindings for GPIB, RS232, and USB instruments

  description: |
    A PyVISA backend that implements a large part of the "Virtual
    Instrument Software Architecture" (VISA) in pure Python (with the
    help of some nice cross platform libraries python packages!).
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/pyvisa/pyvisa-py

extra:
  recipe-maintainers:
    - mtsolmn
    - greyltc
