{% set name = "PyVISA-py" %}
{% set version = "0.3.0" %}
{% set sha256 = "56d69954faaa0769b150ffe67f4158132cd9dd709c20e186a6bd66e8d6577b85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pyvisa >=1.8

  run:
    - python
    - pyvisa >=1.8
    - pyserial # optional
    #- pyusb # optional

test:
  imports:
    - pyvisa

  commands:
    - python -c "import pyvisa.testsuite as ts; ts.run()"

about:
  home: https://github.com/hgrecco/pyvisa-py
  license: MIT
  license_file: LICENSE
  summary: 'Python VISA bindings for GPIB, RS232, and USB instruments'
  license_family: MIT

extra:
  recipe-maintainers:
      - greyltc
