{% set name = "PyVISA-py" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4866e915dd9759023ccaa291e34f0eacbd075539ccaf353ba5dce7a6e0a2bad8

build:
  noarch: python
  number: 2
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - pyvisa >=1.11
    - pyserial
    - pyusb
    - typing_extensions
    - importlib-metadata

test:
  imports:
    - pyvisa
    - pyvisa.testsuite
  commands:
    # fails because of wrong versioning number in seutp.cfg
    # issue raised with project maintainers
    - pip check
    - python -c "import pyvisa.testsuite.testsuite as ts; ts.run()"
    # backend issue with running the below test due to how
    # docker runs and pyvisa detects available visa backends
    # - python -c "import pyvisa; rm = pyvisa.ResourceManager('@py')"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pyvisa/pyvisa-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python VISA bindings for GPIB, RS232, and USB instruments

  description: |
    A PyVISA backend that implements a large part of the "Virtual
    Instrument Software Architecture" (VISA) in pure Python (with the
    help of some nice cross platform libraries python packages!).
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/pyvisa/pyvisa-py

extra:
  recipe-maintainers:
    - MatthieuDartiailh
    - mtsolmn
    - greyltc
