appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vLPoviEb8Iz0ipEQQYgklTgJTycQDmJidMtGlM8RPT2RFvj1VKDO/bnuCYOkXYkRFWlKWQAgwgk6xiw3inu3Qant0DJuIBK3z0ot9ugt+zQ+54RI5eF4gMusATuilwgj7CWIPQULzCryG/9gphmvo8kc3SgulG7vI31y2bjuJx96YgTuBgzC3hbe5DPXUZ9CAES1yrwqJdsRCogu3jISLywTEkrCXO7enVCnL+yDkGGW/GD4YS1H1w58Iwo87cfop3boUf01JZy6oD8R5mibRpBFcphvpi7DEz80gmm3j00keVAFe1JEEcO2S1nVRbv5V72VRrQxfE1n8Us2JqqvI4Vo/oU5qvmwMyPVZ/mh4M72xpl3YN91s2rr5pb0258JeLnGSjlX663llzDra/6BCTkIKh1yTweWpD14KTaF+X4M81ms9Z9XPe1h4jqC2Q/6dFyzmnZM1+ctqRPG/9SQWM/XVl30XWF5SYhluGrcNd2ILpcwCUmipnkdYNyXuRO3EHo7khvhn6nq1Nvkz1do5MotcKxSxt/6VU+jOKHD2QaMIzVxqe/f/ftEjqJ/fZFXuGjqAY0gBk9yF425yWQN5xpfbddoNiqdcseiPdkt9Q1JPx/I8PAzPJwm5bpe28oxrQlm3EsKnDfHbwtRkdW6GfgammSjqqsyi085Iz6J/0s=}
provider: {linux_aarch64: azure, win: azure}
conda_forge_output_validation: true
